version: "3"

services:
  backend:
    build: ./
    container_name: dc_parts_store
    command:
      - ./commands/start_server_${MODE}.sh
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    volumes:
      - static_content:/PartsOnlineStore/src/static/
      - media_content:/PartsOnlineStore/src/media/
      - ./src:/PartsOnlineStore/src
    env_file:
      - .env
    depends_on:
      - mongo
      - postgres

  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - 5434:5432
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    ports:
      - 5000:80
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  mongo:
    image: mongo:4.4.6
    container_name: mongo_cont
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo

  nginx:
    image: nginx
    volumes:
      - static_content:/PartsOnlineStore/src/static/
      - media_content:/PartsOnlineStore/src/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  pg_data: { }
  pgadmin_data: { }
  mongo_data: { }
  static_content: { }
  media_content: { }

